---

- name: Add Unifi {{ unifi_version }} Source
  template:
    src: 100-ubnt-unifi.list.j2
    dest: /etc/apt/sources.list.d/100-ubnt-unifi.list

- name: Add Unifi {{ unifi_version }} GPG Key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 06E85760C0A52C50
    state: present
  register: result
  until: result is success
  retries: 5
  delay: 5

- name: Install Unifi
  apt:
    name: "unifi={{ unifi_version }}*"
    state: present
    update_cache: true
  register: result
  until: result is success
  retries: 5
  delay: 5
